-- CREATES DATABSE hbtn0d_usa AND THE TABLE cities
-- CITIES DESCRIPTION
-- ID INT UNIQUE AUTO GENREATE NOT NULL
-- STATE ID INT CANT BE NULL FOREIGN KEY THE REFRENCES TO ID OF THE STATE TABLE
-- NAME VARCHAR NOT NULL
CREATE DATABASE IF NOT EXISTS hbtn0d_usa;
CREATE TABLE IF NOT EXISTS cities(
    id INT UNIQUE AUT_INCREMENT NOT NULL PRIMARY KEY,
    satte_id INT NOT NULL,
    name VARCHAR(256) NOT NULL,
    FOREIGN KEY (satte_id) REFRENCES states(id)
);